// framework-tests/test-remix/app/routes/login.tsx
import { Form } from '@remix-run/react';
export default function Login() {
  return (
    <div style={{padding:32,maxWidth:400,fontFamily:'system-ui',background:'#0f172a',minHeight:'100vh',color:'#f1f5f9'}}>
      <h1>Sign In</h1>
      <Form method="post" style={{display:'flex',flexDirection:'column',gap:16,marginTop:24}}>
        <input type="email" name="email" placeholder="Email" defaultValue="dev@lunx.dev" required style={{padding:12,borderRadius:8,border:'1px solid #334155',background:'#1e293b',color:'#fff'}}/>
        <input type="password" name="password" placeholder="Password" required style={{padding:12,borderRadius:8,border:'1px solid #334155',background:'#1e293b',color:'#fff'}}/>
        <button type="submit" style={{padding:12,background:'#6366f1',color:'#fff',border:'none',borderRadius:8,cursor:'pointer',fontWeight:600}}>Sign In</button>
      </Form>
    </div>
  );
}

// framework-tests/test-vue/src/pages/Login.vue
<template>
  <div style="padding:32px;max-width:400px">
    <h1>Sign In</h1>
    <div v-if="ok" style="color:#22c55e;margin-top:24px">✅ Welcome back! <RouterLink to="/">Go to shop →</RouterLink></div>
    <form v-else @submit.prevent="ok=true" style="display:flex;flex-direction:column;gap:16px;margin-top:24px">
      <input type="email" placeholder="Email" required style="padding:12px;border-radius:8px;border:1px solid #334155;background:#1e293b;color:#fff"/>
      <input type="password" placeholder="Password" required style="padding:12px;border-radius:8px;border:1px solid #334155;background:#1e293b;color:#fff"/>
      <button type="submit" style="padding:12px;background:#6366f1;color:#fff;border:none;border-radius:8px;cursor:pointer;font-weight:600">Sign In</button>
    </form>
  </div>
</template>
<script setup lang="ts">
import { ref } from 'vue';
const ok = ref(false);
</script>
