// src/templates/starters/angular-spa.ts
/**
 * Angular SPA Starter Template
 * Modern Angular (Standalone) setup with TypeScript
 */

import { TemplateConfig } from '../manager.js';

export const angularSpaTemplate: TemplateConfig = {
    id: 'angular-spa',
    name: 'Angular SPA (Modern)',
    description: 'Modern Angular 17+ Application with Standalone Components',
    framework: 'angular',
    type: 'spa',
    dependencies: {
        "@angular/animations": "^17.0.0",
        "@angular/common": "^17.0.0",
        "@angular/compiler": "^17.0.0",
        "@angular/core": "^17.0.0",
        "@angular/forms": "^17.0.0",
        "@angular/platform-browser": "^17.0.0",
        "@angular/router": "^17.0.0",
        "rxjs": "~7.8.0",
        "tslib": "^2.3.0",
        "zone.js": "~0.14.0"
    },
    devDependencies: {
        "@angular/cli": "^17.0.0",
        "@angular/compiler-cli": "^17.0.0",
        "typescript": "~5.2.0",
        "@nuxc/plugin-angular": "^1.0.0"
    },
    files: {
        'nuxc.config.ts': `
import { defineConfig } from 'nuxc';
import angular from '@nuxc/plugin-angular';

export default defineConfig({
    plugins: [angular()],
    server: {
        port: 4200
    }
});
`,
        'src/main.ts': `
import { bootstrapApplication } from '@angular/platform-browser';
import { appConfig } from './app/app.config';
import { AppComponent } from './app/app.component';

bootstrapApplication(AppComponent, appConfig)
  .catch((err) => console.error(err));
`,
        'src/app/app.config.ts': `
import { ApplicationConfig } from '@angular/core';
import { provideRouter } from '@angular/router';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [provideRouter(routes)]
};
`,
        'src/app/app.routes.ts': `
import { Routes } from '@angular/router';

export const routes: Routes = [];
`,
        'src/app/app.component.ts': `
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'nuxc-angular';
}
`,
        'src/app/app.component.html': `
<main class="main">
  <div class="content">
    <h1>Nuxc + Angular 17</h1>
    <p>Build with speed.</p>
  </div>
</main>
<router-outlet></router-outlet>
`,
        'src/app/app.component.css': `
.main {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  font-family: 'Inter', sans-serif;
}
h1 {
  color: #c3002f;
}
`,
        'src/index.html': `
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{{PROJECT_NAME}}</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
<body>
  <app-root></app-root>
</body>
</html>
`,
        'tsconfig.json': `
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "declaration": false,
    "experimentalDecorators": true,
    "moduleResolution": "bundler",
    "importHelpers": true,
    "target": "ES2022",
    "module": "ES2022",
    "lib": [
      "ES2022",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
`
    }
};

// src/templates/starters/react-spa.ts
/**
 * React SPA Starter Template
 * Production-ready React 18+ setup with TypeScript
 */

import { TemplateConfig } from '../manager.js';

export const reactSpaTemplate: TemplateConfig = {
    id: 'react-spa',
    name: 'React SPA (TypeScript)',
    description: 'Modern React 18+ Single Page Application with TypeScript',
    framework: 'react',
    type: 'spa',
    dependencies: {
        "react": "^18.2.0",
        "react-dom": "^18.2.0"
    },
    devDependencies: {
        "@types/react": "^18.2.0",
        "@types/react-dom": "^18.2.0",
        "@nuxc/plugin-react": "^1.0.0"
    },
    files: {
        'nuxc.config.ts': `
import { defineConfig } from 'nuxc';
import react from '@nuxc/plugin-react';

export default defineConfig({
    plugins: [react()],
    server: {
        port: 3000,
        open: true
    }
});
`,
        'src/main.tsx': `
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.js'; // Note: .js extension for ESM
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
`,
        'src/App.tsx': `
import React, { useState } from 'react';
import './App.css';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="App">
      <header className="App-header">
        <h1>Nuxc + React</h1>
        <div className="card">
          <button onClick={() => setCount((count) => count + 1)}>
            count is {count}
          </button>
          <p>
            Edit <code>src/App.tsx</code> and save to test HMR
          </p>
        </div>
        <p className="read-the-docs">
          Click on the Nuxc logo to learn more
        </p>
      </header>
    </div>
  );
}

export default App;
`,
        'src/index.css': `
:root {
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  font-weight: 400;
  color-scheme: light dark;
  color: rgba(255, 255, 255, 0.87);
  background-color: #242424;
  font-synthesis: none;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

body {
  margin: 0;
  display: flex;
  place-items: center;
  min-width: 320px;
  min-height: 100vh;
}

h1 {
  font-size: 3.2em;
  line-height: 1.1;
}

button {
  border-radius: 8px;
  border: 1px solid transparent;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  font-family: inherit;
  background-color: #1a1a1a;
  cursor: pointer;
  transition: border-color 0.25s;
}
button:hover {
  border-color: #646cff;
}
button:focus,
button:focus-visible {
  outline: 4px auto -webkit-focus-ring-color;
}
`,
        'src/App.css': `
#root {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}

.card {
  padding: 2em;
}

.read-the-docs {
  color: #888;
}
`,
        'src/vite-env.d.ts': `/// <reference types="vite/client" />`,
        'index.html': `
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{PROJECT_NAME}}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`
    }
};
